alias ll="ls -lh -a"

alias ..="z ../"
alias ...="z ../../"
alias ....="z ../../../"

alias ga="git add"
alias gaa="git add --all"
alias gco="git checkout"
alias gcmsg="git commit -m"
alias gca="git commit --amend"
alias gms="git maintenance start"
alias gpl="git pull"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias gr="git restore"
alias grs="git restore --staged"
alias gst="git status"
alias gs="git switch"
alias gcb="git switch -c"
alias gsm="git switch main"
alias gcm="git switch main"
