alias ll="eza -l -a --git --git-repos --icons"
alias lt="eza -l -a --git --git-repos --icons -T"

alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"

alias ga="git add"
alias gaa="git add --all"
alias gco="git checkout"
alias gcmsg="git commit -m"
alias gca="git commit --amend"
alias gms="git maintenance start"
alias gpl="git pull"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias gr="git restore"
alias grs="git restore --staged"
alias gst="git status -s -b"
alias gs="git switch"
alias gcb="git switch -c"
alias gsm="git switch main"
alias gcm="git switch main"
